import assert from "node:assert/strict";
import { artifactAcceptanceInstruction, checkArtifactCompletion } from "../lib/ai/artifact-completion";
import { assessArtifact, artifactScriptError } from "../lib/ai/navi-soul/artifact-quality";
import { createArtifactGate } from "../lib/ai/artifact-gate";

const header = '{"id":"museum","title":"Museum","kind":"html","height":420}';
const fence = (html: string) => `\`\`\`navi-artifact\n${header}\n---\n${html}\n\`\`\``;
const brokenMuseum = '<div id="room"></div><button id="next">Next century</button><script>function renderRoom(){ const current = 0;';
assert.equal(checkArtifactCompletion(fence(brokenMuseum)).ok, false, "the observed half-written museum must never be delivered");
assert.equal(checkArtifactCompletion(`\`\`\`navi-artifact\n${header}\n---\n${brokenMuseum}`).ok, false);
assert.equal(checkArtifactCompletion(fence('<div id="room">Museum</div><script>const current = ;</script>')).ok, false, "closed tags do not make invalid JavaScript executable");
const good = '<div id="room">Welcome to the museum</div><button id="next">Enter</button><script>document.getElementById("next").addEventListener("click", () => { document.getElementById("room").textContent = "Gallery"; });</script>';
assert.deepEqual(checkArtifactCompletion(fence(good)), { ok: true, count: 1 });
assert.deepEqual(checkArtifactCompletion(`${fence(good)}\n${fence(good)}`), { ok: true, count: 2 });
assert.equal(checkArtifactCompletion("I created your museum.").ok, false);
assert.equal(artifactScriptError('<script>globalThis.mustNeverExecute = true;</script>'), null);
assert.equal((globalThis as Record<string, unknown>).mustNeverExecute, undefined, "validation parses but never executes generated code");
assert.match(artifactScriptError('<script src="https://example.com/library.js"></script>')!, /External/);
assert.equal(artifactScriptError('<script type="application/json">{"title":"Museum"}</script>'), null);
assert.equal(assessArtifact(JSON.stringify({ id: "m", title: "M", kind: "html", html: brokenMuseum })).ok, false);
const gate = createArtifactGate();
const output = gate.push(`\`\`\`navi-artifact\n${header}\n---\n${brokenMuseum}`) + gate.flush();
assert.ok(!output.includes("```navi-artifact"), "partial salvage cannot bypass the script check");
assert.match(artifactAcceptanceInstruction("a museum I can walk around"), /camera position/);
assert.ok(!artifactAcceptanceInstruction("make a tip calculator").includes("raycast"));
console.log("Artifact completion regressions passed.");
