import { readFileSync } from 'node:fs';
const src = readFileSync('app/api/chat/route.ts','utf8');
const body = src.slice(src.indexOf('function redactSecrets'), src.indexOf('\n}\n', src.indexOf('function redactSecrets'))+2);
const js = body.replace(/: string/g,'').replace(/\)\s*\{/, ') {');
const redact = new Function(`${js}; return redactSecrets;`)();
let pass=0,fail=0;
const check=(n,a,e)=>{const ok=a===e;ok?pass++:fail++;console.log(`${ok?'PASS':'FAIL'}  ${n}${ok?'':`\n   got:  ${a}\n   want: ${e}`}`)};
check('groq key', redact('bad key gsk_abcdefgh12345678zz'), 'bad key [redacted]');
check('openai style', redact('sk-proj-abcdefgh12345678'), '[redacted]');
check('hf token', redact('token hf_QQQQwwwweeeerrrr'), 'token [redacted]');
check('google key', redact('key=AIzaSyABCDEFGHIJKLMNOP failed'), 'key=[redacted] failed');
check('bearer header', redact('Authorization: Bearer eyJhbGciOi.JzdWIiOiIx.abc'), 'Authorization: Bearer [redacted]');
check('json field', redact('{"api_key":"abcdefgh123456"}'), '{"api_key":"[redacted]"}');
check('ordinary text untouched', redact('Gemini returned 400: model overloaded'), 'Gemini returned 400: model overloaded');
console.log(`\n${pass}/${pass+fail} passed`);
process.exit(fail?1:0);
