import { test } from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import { zipSync,strToU8 } from 'fflate';
import { StreamParser,readSSE } from '../lib/streaming/parser';
import { MCPBus,callFingerprint,type ExecutionSession } from '../lib/tools/mcp-bus';
import { validateArtifact,compileComponent } from '../lib/sandbox/runtime';
import { LocalStore,applyUnifiedDiff } from '../lib/storage/store';
import { calculate } from '../lib/tools/builtins';
import { parseCSV,parseDocument,chunkText } from '../lib/workers/document-parser';
import { NaviRouter,type ModelNode } from '../lib/ai/router';
const html='<button id="count">0</button><script>document.getElementById("count").addEventListener("click",event=>event.target.textContent=Number(event.target.textContent)+1)</script>';
test('every streaming boundary preserves artifact content and hides thought bodies',()=>{
  const source='Hello <thought>private reasoning</thought><artifact id="x" kind="html">'+html+'</artifact> Done';
  for(let split=1;split<source.length;split++){const parser=new StreamParser();const events=[...parser.push(source.slice(0,split)),...parser.push(source.slice(split)),...parser.finish()];assert.equal(events.filter(e=>e.type==='text').map(e=>e.value).join(''),'Hello  Done');assert.equal(events.filter(e=>e.type==='artifact').map(e=>e.value).join(''),html);assert.ok(!JSON.stringify(events).includes('private reasoning'));}
});
test('unfinished and oversized structured output rejects cleanly',()=>{let parser=new StreamParser(20);assert.ok(parser.push('<artifact>'+'x'.repeat(21)).some(e=>e.type==='error'));parser=new StreamParser();parser.push('<artifact>unfinished');assert.equal(parser.finish()[0].type,'error');});
test('SSE handles byte boundaries and CRLF',async()=>{const bytes=new TextEncoder().encode('data: {"text":"שלום"}\r\n\r\ndata: [DONE]\n\n');const stream=new ReadableStream<Uint8Array>({start(c){for(const b of bytes)c.enqueue(new Uint8Array([b]));c.close();}});const frames=[];for await(const data of readSSE(stream))frames.push(data);assert.deepEqual(frames,['{"text":"שלום"}','[DONE]']);});
test('artifact validation parses JS without executing it',async()=>{await assert.rejects(validateArtifact({source:'<div>Broken</div><script>const x =',kind:'html'}));await assert.rejects(validateArtifact({source:'<script>const x=;</script>',kind:'html'}));assert.equal((await validateArtifact({source:html,id:'counter',kind:'html'})).id,'counter');assert.ok(compileComponent('export default function App(){return <button>Ready</button>}').includes('createElement'));assert.throws(()=>compileComponent('import x from "unsafe-package"; export default x'));});
test('artifact revisions are immutable and reject stale patches',async()=>{const store=new LocalStore('test-'+crypto.randomUUID());const a=await validateArtifact({id:'counter',kind:'html',source:html});const v1=await store.saveArtifact(a);const edited=await validateArtifact({...a,source:html.replace('>0<','>1<')});const v2=await store.saveArtifact(edited,v1.hash);assert.equal(v2.version,2);assert.equal((await store.versions(a.id))[0].source,html);await assert.rejects(store.saveArtifact(a,v1.hash));await store.close();});
test('unified patches require exact context and correct counts',()=>{assert.equal(applyUnifiedDiff('a\nb\nc','@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n'),'a\nB\nc');assert.throws(()=>applyUnifiedDiff('wrong','@@ -1 +1 @@\n-a\n+b\n'));});
const session=():ExecutionSession=>({principal:'test',signal:new AbortController().signal,remaining:20,maxDepth:2,approvedCalls:new Set()});
test('tool bus scales beyond fifty registered tools and validates schemas',async()=>{const bus=new MCPBus();for(let i=0;i<55;i++)bus.register({name:'read_'+i,description:'read',effect:'read',inputSchema:{type:'object',properties:{n:{type:'number'}},required:['n'],additionalProperties:false},execute:async args=>(args as {n:number}).n*2});assert.equal(bus.list().length,55);const result=await bus.execute({id:'1',name:'read_50',arguments:{n:3}},session());assert.equal(result.value,6);const bad=await bus.execute({id:'2',name:'read_50',arguments:{n:'bad'}},session());assert.equal(bad.error?.code,'INVALID_ARGUMENTS');});
test('writes require approval of exact arguments and are not silently retried',async()=>{const bus=new MCPBus();let writes=0;bus.register({name:'write',description:'write',effect:'write',inputSchema:{type:'object'},execute:async()=>++writes});const call={id:'1',name:'write',arguments:{a:1}};const s=session();assert.equal((await bus.execute(call,s)).error?.code,'APPROVAL_REQUIRED');s.approvedCalls.add(await callFingerprint(call));assert.equal((await bus.execute(call,s)).value,1);assert.equal((await bus.execute({...call,arguments:{a:2}},s)).error?.code,'APPROVAL_REQUIRED');assert.equal(writes,1);});
test('tool timeouts and recursive budget exhaustion become structured errors',async()=>{const bus=new MCPBus();bus.register({name:'stall',description:'stall',effect:'read',timeoutMs:100,inputSchema:{type:'object'},execute:async()=>new Promise(()=>{})});assert.equal((await bus.execute({id:'1',name:'stall',arguments:{}},session())).error?.code,'TIMEOUT');bus.register({name:'recursive',description:'recursive',effect:'read',inputSchema:{type:'object'},execute:async(_,c)=>c.invoke({id:'child',name:'recursive',arguments:{}})});const result=await bus.execute({id:'1',name:'recursive',arguments:{}},session());assert.ok(JSON.stringify(result).includes('BUDGET_EXHAUSTED'));});
test('CSV quote boundaries and deterministic arithmetic',()=>{assert.deepEqual(parseCSV('name,value\r\n"hello, world","line1\nline2"'),[['name','value'],['hello, world','line1\nline2']]);assert.throws(()=>parseCSV('"unfinished'));assert.equal(calculate('(12+3)*2'),30);assert.throws(()=>calculate('process.exit()'));assert.throws(()=>calculate('1/0'));});
test('DOCX and XLSX parse locally from real ZIP structures',async()=>{
  const docx=zipSync({'word/document.xml':strToU8('<w:document><w:body><w:p><w:r><w:t>Hello from a document</w:t></w:r></w:p></w:body></w:document>')});const doc=await parseDocument({id:'1',name:'test.docx',buffer:docx.slice().buffer});assert.match(doc.text,/Hello from a document/);
  const xlsx=zipSync({'xl/worksheets/sheet1.xml':strToU8('<worksheet><sheetData><row><c r="A1"><v>42</v></c></row></sheetData></worksheet>')});assert.match((await parseDocument({id:'2',name:'test.xlsx',buffer:xlsx.slice().buffer})).text,/42/);assert.ok(chunkText('sentence '.repeat(1000)).every(c=>c.text.length<=2200));
});
const node=(id:string):ModelNode=>({id,endpoint:'https://example.com/'+id,key:'test',model:id,role:'fast',free:true,context:16000,maxOutput:4000,tools:true});
const streamed=(frames:unknown[])=>new Response(new ReadableStream({start(c){for(const frame of frames)c.enqueue(new TextEncoder().encode('data: '+JSON.stringify(frame)+'\n\n'));c.enqueue(new TextEncoder().encode('data: [DONE]\n\n'));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});
test('router keeps the client stream alive across a rejected provider',async()=>{let calls=0;const router=new NaviRouter({nodes:[node('a'),node('b')],bus:new MCPBus(),fetch:async()=>++calls===1?new Response('',{status:403}):streamed([{choices:[{delta:{content:'Recovered answer'}}]}])});const events=[];for await(const event of router.run({messages:[{role:'user',content:'Hello there'}],principal:'u',signal:new AbortController().signal}))events.push(event);assert.equal(calls,2);assert.equal(events.filter(e=>e.type==='text').map(e=>'text'in e?e.text:'').join(''),'Recovered answer');assert.equal(events.at(-1)?.type,'done');});
test('router repairs broken artifacts before delivery',async()=>{let calls=0;const router=new NaviRouter({nodes:[node('a')],bus:new MCPBus(),fetch:async()=>streamed([{choices:[{delta:{content:++calls===1?'<artifact id="a" kind="html"><div>Broken</div><script>const x=</artifact>':`<artifact id="a" kind="html">${html}</artifact>`}}]}])});const events=[];for await(const event of router.run({messages:[{role:'user',content:'Create an interactive calculator artifact'}],principal:'u',signal:new AbortController().signal}))events.push(event);assert.equal(calls,2);assert.equal(events.filter(e=>e.type==='artifact').length,1);assert.ok(!events.some(e=>e.type==='error'));});
