"""Generate iOS PWA launch images and the link table that declares them.

Without apple-touch-startup-image, an installed PWA shows a blank white
screen while the shell boots. Each image is the app background with the
brand spark centred, so the splash hands off to the launch surface with
nothing visibly changing but the content fading in.

Run from the repo root after changing the brand mark or the app
background: `python3 scripts/generate-splash.py`.
"""
import os
from PIL import Image

OUT = "public/splash"
SPARK = "public/brand-spark.png"
BG = {"dark": (0x26, 0x26, 0x24, 255), "light": (0xFA, 0xF9, 0xF5, 255)}

# (css width, css height, dpr) — covers iPhone SE through 16 Pro Max and iPads.
DEVICES = [
    (320, 568, 2), (375, 667, 2), (375, 812, 3), (390, 844, 3),
    (393, 852, 3), (402, 874, 3), (414, 736, 3), (414, 896, 2),
    (414, 896, 3), (428, 926, 3), (430, 932, 3), (440, 956, 3),
    (768, 1024, 2), (810, 1080, 2), (820, 1180, 2), (834, 1112, 2),
    (834, 1194, 2), (1024, 1366, 2),
]

spark = Image.open(SPARK).convert("RGBA")
os.makedirs(OUT, exist_ok=True)
entries = []

for css_w, css_h, dpr in DEVICES:
    for orientation in ("portrait", "landscape"):
        w, h = (css_w, css_h) if orientation == "portrait" else (css_h, css_w)
        for scheme, bg in BG.items():
            px_w, px_h = w * dpr, h * dpr
            canvas = Image.new("RGBA", (px_w, px_h), bg)
            # Same optical weight as the launch surface mark at every size.
            size = max(96, int(min(px_w, px_h) * 0.22))
            mark = spark.resize((size, size), Image.LANCZOS)
            canvas.alpha_composite(mark, ((px_w - size) // 2, (px_h - size) // 2))
            name = f"{w}x{h}@{dpr}x-{scheme}.png"
            # A flat background and one gradient mark quantise without visible
            # loss, and it takes the set from ~3.5 MB down to under 1 MB.
            canvas.convert("RGB").quantize(colors=64, method=Image.MEDIANCUT).save(
                os.path.join(OUT, name), optimize=True
            )
            entries.append({
                "href": f"/splash/{name}",
                "media": (
                    f"(prefers-color-scheme: {scheme}) and "
                    f"(device-width: {css_w}px) and (device-height: {css_h}px) and "
                    f"(-webkit-device-pixel-ratio: {dpr}) and (orientation: {orientation})"
                ),
            })

lines = [
    "// Generated by scripts/generate-splash.py — do not edit by hand.",
    "",
    "export type SplashScreen = { href: string; media: string };",
    "",
    "export const SPLASH_SCREENS: SplashScreen[] = [",
]
for entry in entries:
    lines.append(f'  {{ href: "{entry["href"]}", media: "{entry["media"]}" }},')
lines += ["];", ""]

with open("lib/ui/splash-screens.ts", "w") as fh:
    fh.write("\n".join(lines))

total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
print(f"{len(entries)} images, {total / 1024:.0f} KB total")
